name: Old Stortfordian Lodge
favicon: null
layout_spectrum: 0.24093
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7f6a3b'
    - '#a1916f'
    - '#bfb49d'
    - '#342c1f'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.7290688855573535
purpose: []
