favicon: null
name: Old Stortfordian Lodge
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3829787
  brandStrength: 0.7808511
  lightness: 0.7212766
  brandColors:
    - '#ffffff'
    - '#7f6a3b'
    - '#a1916f'
    - '#bfb49d'
    - '#342c1f'
  rhythmicContrast: 0
typography_spectrum: 1
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
